#!/usr/bin/env python3
"""
MemBrain PEBS Memory Profiler
Profiles memory allocation access frequency and physical Peak RSS per site_id.
"""

import os
import sys
import time
import subprocess
import argparse

from profiler_core import (
    parse_allocation_sites,
    load_site_rss_profile,
    parse_alloc_trace,
    parse_pebs_perf_data,
    export_profile_json
)

def run_pebs_profiling(cmd, runtime_lib, sites_file, output_file, sample_period=512, sample_interval=0.5):
    sites = parse_allocation_sites(sites_file)
    if not sites:
        print("[PEBS Profiler] No allocation sites found to profile.", file=sys.stderr)
        sys.exit(1)

    # Cleanup old trace files
    for old_file in ["alloc_trace.txt", "pebs_perf.data", "site_rss_profile.json"]:
        if os.path.exists(old_file):
            os.remove(old_file)

    env = os.environ.copy()
    ld_path = env.get("LD_LIBRARY_PATH", "")
    runtime_dir = os.path.dirname(os.path.abspath(runtime_lib))
    env["LD_LIBRARY_PATH"] = f"{runtime_dir}:{ld_path}"
    env["MEMBRAIN_VERBOSE"] = "1"
    env["MEMBRAIN_TRACE"] = "1"
    env["MEMBRAIN_PROFILE"] = "1"

    print(f"[PEBS Profiler] Launching target command under PEBS (period={sample_period}) & pagemap profiling: {' '.join(cmd)}")
    start_time = time.time()
    
    # Launch process under perf record with -c sample_period and -d flag for memory load data addresses (L3 misses)
    perf_cmd = ["perf", "record", "-e", "mem_load_retired.l3_miss:pp", "-c", str(sample_period), "-d", "-o", "pebs_perf.data"] + cmd
    
    try:
        proc = subprocess.Popen(perf_cmd, env=env)
    except FileNotFoundError:
        print("[PEBS Profiler] Error: 'perf' executable not found.", file=sys.stderr)
        sys.exit(1)

    peak_process_rss = 0
    page_size = os.sysconf('SC_PAGE_SIZE')

    def get_process_tree_rss(pid):
        total_rss = 0
        try:
            pids_to_check = [pid]
            while pids_to_check:
                curr_pid = pids_to_check.pop(0)
                try:
                    with open(f"/proc/{curr_pid}/statm", "r") as f:
                        pages = int(f.read().split()[1])
                        total_rss += pages * page_size
                except (FileNotFoundError, ProcessLookupError, IndexError):
                    pass

                try:
                    with open(f"/proc/{curr_pid}/task/{curr_pid}/children", "r") as f:
                        children = [int(c) for c in f.read().split()]
                        pids_to_check.extend(children)
                except (FileNotFoundError, ProcessLookupError, ValueError):
                    pass
        except Exception:
            pass
        return total_rss

    while proc.poll() is None:
        current_rss = get_process_tree_rss(proc.pid)
        if current_rss > peak_process_rss:
            peak_process_rss = current_rss
        time.sleep(sample_interval)

    ret_code = proc.wait()
    if ret_code != 0:
        print(f"[PEBS Profiler] Error: Target command or perf record failed with exit code {ret_code}.", file=sys.stderr)
        sys.exit(ret_code)

    elapsed = time.time() - start_time
    print(f"[PEBS Profiler] Target finished in {elapsed:.2f} seconds. Peak Process RSS: {peak_process_rss / (1024*1024):.2f} MB")

    # Validate presence of allocation trace and PEBS perf data
    if not os.path.exists("alloc_trace.txt"):
        print("[PEBS Profiler] Error: 'alloc_trace.txt' was not generated by libmembrain_rt.so!", file=sys.stderr)
        sys.exit(1)

    if not os.path.exists("pebs_perf.data"):
        print("[PEBS Profiler] Error: 'pebs_perf.data' was not generated by perf record!", file=sys.stderr)
        sys.exit(1)

    # Parse allocation trace and PEBS memory samples
    regions, fallback_site_rss = parse_alloc_trace("alloc_trace.txt")
    if not regions:
        print("[PEBS Profiler] Error: No valid allocation regions found in alloc_trace.txt!", file=sys.stderr)
        sys.exit(1)

    # Load physical Peak RSS measured via pagemap_util
    site_rss_map = load_site_rss_profile("site_rss_profile.json")

    site_access_counts = parse_pebs_perf_data("pebs_perf.data", regions)

    # Export profile_data.json
    export_profile_json(sites, site_access_counts, site_rss_map, fallback_site_rss, output_file)

def main():
    parser = argparse.ArgumentParser(description="MemBrain PEBS Memory Profiler")
    parser.add_argument("--sites", default="allocation_sites.json", help="Path to allocation_sites.json")
    parser.add_argument("--runtime", default="../build/runtime/libmembrain_rt.so", help="Path to libmembrain_rt.so")
    parser.add_argument("--output", default="profile_data.json", help="Output profile data JSON path")
    parser.add_argument("--sample-period", "--sample-rate", type=int, default=512, help="PEBS sample period/rate (LLC misses per sample, default: 512)")
    parser.add_argument("cmd", nargs=argparse.REMAINDER, help="Target application command")

    args = parser.parse_args()
    if not args.cmd:
        parser.print_help()
        sys.exit(1)

    run_pebs_profiling(args.cmd, args.runtime, args.sites, args.output, sample_period=args.sample_period)

if __name__ == "__main__":
    main()
