#!/usr/bin/env python3
"""
MemBrain PEBS Memory Profiler
Profiles memory allocation access frequency and physical Peak RSS per site_id.
"""

import os
import sys
import time
import subprocess
import argparse

from profiler_core import (
    parse_allocation_sites,
    load_site_rss_profile,
    parse_alloc_trace,
    parse_pebs_perf_data,
    export_profile_json
)

def run_pebs_profiling(cmd, runtime_lib, sites_file, output_file, sample_interval=0.5):
    sites = parse_allocation_sites(sites_file)
    if not sites:
        print("[PEBS Profiler] No allocation sites found to profile.", file=sys.stderr)
        sys.exit(1)

    # Cleanup old trace files
    for old_file in ["alloc_trace.txt", "pebs_perf.data", "site_rss_profile.json"]:
        if os.path.exists(old_file):
            os.remove(old_file)

    env = os.environ.copy()
    ld_path = env.get("LD_LIBRARY_PATH", "")
    runtime_dir = os.path.dirname(os.path.abspath(runtime_lib))
    env["LD_LIBRARY_PATH"] = f"{runtime_dir}:{ld_path}"
    env["MEMBRAIN_VERBOSE"] = "1"
    env["MEMBRAIN_TRACE"] = "1"
    env["MEMBRAIN_PROFILE"] = "1"

    print(f"[PEBS Profiler] Launching target command under PEBS & pagemap profiling: {' '.join(cmd)}")
    start_time = time.time()
    
    # Launch process under perf record for memory loads
    perf_cmd = ["perf", "record", "-e", "mem_inst_retired.all_loads:pp", "-o", "pebs_perf.data"] + cmd
    
    try:
        proc = subprocess.Popen(perf_cmd, env=env, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    except FileNotFoundError:
        print("[PEBS Profiler] Error: 'perf' executable not found.", file=sys.stderr)
        sys.exit(1)

    peak_process_rss = 0
    while proc.poll() is None:
        try:
            with open(f"/proc/{proc.pid}/statm", "r") as f:
                pages = int(f.read().split()[1])
                rss_bytes = pages * os.sysconf('SC_PAGE_SIZE')
                if rss_bytes > peak_process_rss:
                    peak_process_rss = rss_bytes
        except (FileNotFoundError, ProcessLookupError, IndexError):
            pass
        time.sleep(sample_interval)

    stdout, stderr = proc.communicate()
    if proc.returncode != 0:
        print(f"[PEBS Profiler] Error: Target command or perf record failed with exit code {proc.returncode}.", file=sys.stderr)
        if stderr:
            print(f"[PEBS Profiler] Stderr: {stderr}", file=sys.stderr)
        sys.exit(proc.returncode)

    elapsed = time.time() - start_time
    print(f"[PEBS Profiler] Target finished in {elapsed:.2f} seconds. Peak Process RSS: {peak_process_rss / (1024*1024):.2f} MB")

    # Validate presence of allocation trace and PEBS perf data
    if not os.path.exists("alloc_trace.txt"):
        print("[PEBS Profiler] Error: 'alloc_trace.txt' was not generated by libmembrain_rt.so!", file=sys.stderr)
        sys.exit(1)

    if not os.path.exists("pebs_perf.data"):
        print("[PEBS Profiler] Error: 'pebs_perf.data' was not generated by perf record!", file=sys.stderr)
        sys.exit(1)

    # Parse allocation trace and PEBS memory samples
    regions, fallback_site_rss = parse_alloc_trace("alloc_trace.txt")
    if not regions:
        print("[PEBS Profiler] Error: No valid allocation regions found in alloc_trace.txt!", file=sys.stderr)
        sys.exit(1)

    # Load physical Peak RSS measured via pagemap_util
    site_rss_map = load_site_rss_profile("site_rss_profile.json")

    site_access_counts = parse_pebs_perf_data("pebs_perf.data", regions)

    # Export profile_data.json
    export_profile_json(sites, site_access_counts, site_rss_map, fallback_site_rss, output_file)

def main():
    parser = argparse.ArgumentParser(description="MemBrain PEBS Memory Profiler")
    parser.add_argument("--sites", default="allocation_sites.json", help="Path to allocation_sites.json")
    parser.add_argument("--runtime", default="../build/runtime/libmembrain_rt.so", help="Path to libmembrain_rt.so")
    parser.add_argument("--output", default="profile_data.json", help="Output profile data JSON path")
    parser.add_argument("cmd", nargs=argparse.REMAINDER, help="Target application command")

    args = parser.parse_args()
    if not args.cmd:
        parser.print_help()
        sys.exit(1)

    run_pebs_profiling(args.cmd, args.runtime, args.sites, args.output)

if __name__ == "__main__":
    main()
