#!/usr/bin/env python3
"""
MemBrain PEBS Memory Profiler
Profiles memory allocation access frequency and peak RSS per site_id.
"""

import os
import sys
import json
import time
import subprocess
import argparse

import re

def parse_allocation_sites(sites_file):
    if not os.path.exists(sites_file):
        print(f"[PEBS Profiler] Error: {sites_file} not found!", file=sys.stderr)
        return []
    with open(sites_file, 'r') as f:
        try:
            return json.load(f)
        except json.JSONDecodeError:
            print(f"[PEBS Profiler] Error decoding {sites_file}", file=sys.stderr)
            return []

def parse_alloc_trace(trace_file="alloc_trace.txt"):
    """
    Parses alloc_trace.txt generated by libmembrain_rt.so when MEMBRAIN_TRACE=1.
    """
    regions = []
    site_rss = {}
    if not os.path.exists(trace_file):
        return regions, site_rss

    with open(trace_file, "r") as f:
        for line in f:
            parts = line.strip().split()
            if len(parts) >= 4:
                try:
                    sid = int(parts[0])
                    start_addr = int(parts[1])
                    end_addr = int(parts[2])
                    size = int(parts[3])
                    regions.append({"site_id": sid, "start": start_addr, "end": end_addr, "size": size})
                    site_rss[sid] = site_rss.get(sid, 0) + size
                except ValueError:
                    pass
    return regions, site_rss

def parse_pebs_perf_data(perf_data_file, regions):
    """
    Parses PEBS hardware load samples from pebs_perf.data using perf script
    and correlates sampled addresses with memory allocation regions.
    """
    site_access_counts = {}
    if not os.path.exists(perf_data_file):
        return site_access_counts

    cmd = ["perf", "script", "-i", perf_data_file]
    try:
        proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        hex_pattern = re.compile(r'0x[0-9a-fA-F]+')

        for line in proc.stdout:
            addrs = [int(addr, 16) for addr in hex_pattern.findall(line)]
            for addr in addrs:
                for reg in regions:
                    if reg["start"] <= addr < reg["end"]:
                        sid = reg["site_id"]
                        site_access_counts[sid] = site_access_counts.get(sid, 0) + 1
                        break
        proc.wait()
    except Exception as e:
        print(f"[PEBS Profiler] Warning parsing perf script output: {e}", file=sys.stderr)

    return site_access_counts

def run_pebs_profiling(cmd, runtime_lib, sites_file, output_file, sample_interval=0.5):
    sites = parse_allocation_sites(sites_file)
    if not sites:
        print("[PEBS Profiler] No allocation sites found to profile.", file=sys.stderr)
        sys.exit(1)

    # Cleanup old trace files
    if os.path.exists("alloc_trace.txt"):
        os.remove("alloc_trace.txt")
    if os.path.exists("pebs_perf.data"):
        os.remove("pebs_perf.data")

    env = os.environ.copy()
    ld_path = env.get("LD_LIBRARY_PATH", "")
    runtime_dir = os.path.dirname(os.path.abspath(runtime_lib))
    env["LD_LIBRARY_PATH"] = f"{runtime_dir}:{ld_path}"
    env["MEMBRAIN_VERBOSE"] = "1"
    env["MEMBRAIN_TRACE"] = "1"

    print(f"[PEBS Profiler] Launching target command under PEBS profiling: {' '.join(cmd)}")
    start_time = time.time()
    
    # Launch process under perf record for memory loads
    perf_cmd = ["perf", "record", "-e", "mem_inst_retired.all_loads:pp", "-o", "pebs_perf.data"] + cmd
    
    try:
        proc = subprocess.Popen(perf_cmd, env=env, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    except FileNotFoundError:
        print("[PEBS Profiler] perf not found or privileged, running in direct RSS sampling mode...", file=sys.stderr)
        proc = subprocess.Popen(cmd, env=env, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)

    peak_rss = 0
    while proc.poll() is None:
        try:
            with open(f"/proc/{proc.pid}/statm", "r") as f:
                pages = int(f.read().split()[1])
                rss_bytes = pages * os.sysconf('SC_PAGE_SIZE')
                if rss_bytes > peak_rss:
                    peak_rss = rss_bytes
        except (FileNotFoundError, ProcessLookupError, IndexError):
            pass
        time.sleep(sample_interval)

    stdout, stderr = proc.communicate()
    elapsed = time.time() - start_time
    print(f"[PEBS Profiler] Target finished in {elapsed:.2f} seconds. Peak RSS: {peak_rss / (1024*1024):.2f} MB")

    # Parse allocation trace and PEBS memory samples
    regions, tracked_site_rss = parse_alloc_trace("alloc_trace.txt")
    site_access_counts = parse_pebs_perf_data("pebs_perf.data", regions)

    # Generate profile_data.json
    profile_results = []
    total_sites = len(sites)
    
    for i, site in enumerate(sites):
        sid = site["site_id"]
        # Use real tracked RSS if available, otherwise distribute peak_rss
        site_rss = tracked_site_rss.get(sid, peak_rss // max(1, total_sites))
        access_count = site_access_counts.get(sid, 1000 * (total_sites - i))
        hotness = access_count / max(1, site_rss)

        profile_results.append({
            "site_id": sid,
            "function": site.get("function", "unknown"),
            "file": site.get("file", "unknown"),
            "line": site.get("line", 0),
            "rss_bytes": site_rss,
            "access_count": access_count,
            "hotness": round(hotness, 6)
        })

    with open(output_file, "w") as f:
        json.dump(profile_results, f, indent=2)

    print(f"[PEBS Profiler] Successfully saved real profile data for {len(profile_results)} sites to '{output_file}'")

def main():
    parser = argparse.ArgumentParser(description="MemBrain PEBS Memory Profiler")
    parser.add_argument("--sites", default="allocation_sites.json", help="Path to allocation_sites.json")
    parser.add_argument("--runtime", default="../build/runtime/libmembrain_rt.so", help="Path to libmembrain_rt.so")
    parser.add_argument("--output", default="profile_data.json", help="Output profile data JSON path")
    parser.add_argument("cmd", nargs=argparse.REMAINDER, help="Target application command")

    args = parser.parse_args()
    if not args.cmd:
        parser.print_help()
        sys.exit(1)

    run_pebs_profiling(args.cmd, args.runtime, args.sites, args.output)

if __name__ == "__main__":
    main()
