"""
MemBrain Profiler Core Module
Contains shared helper functions for profilers:
- parse_allocation_sites: Loads allocation_sites.json
- load_site_rss_profile: Loads physical Peak RSS profile generated by libmembrain_rt.so (pagemap_util)
- parse_alloc_trace: Parses alloc_trace.txt
- export_profile_json: Merges physical Peak RSS with hardware counters and outputs profile_data.json
"""

import os
import sys
import json
import re
import subprocess

def parse_allocation_sites(sites_file):
    if not os.path.exists(sites_file):
        print(f"[ProfilerCore] Error: {sites_file} not found!", file=sys.stderr)
        sys.exit(1)
    with open(sites_file, 'r') as f:
        try:
            return json.load(f)
        except json.JSONDecodeError as e:
            print(f"[ProfilerCore] Error decoding {sites_file}: {e}", file=sys.stderr)
            sys.exit(1)

def load_site_rss_profile(rss_profile_file="site_rss_profile.json"):
    """
    Loads per-site physical Peak RSS profile generated by libmembrain_rt.so (pagemap_util).
    """
    if not os.path.exists(rss_profile_file):
        print(f"[ProfilerCore] Error: '{rss_profile_file}' not found!", file=sys.stderr)
        sys.exit(1)

    site_rss_map = {}
    try:
        with open(rss_profile_file, "r") as f:
            data = json.load(f)
            if isinstance(data, list):
                for item in data:
                    sid = item.get("site_id")
                    peak_rss = item.get("peak_rss_bytes", 0)
                    if sid is not None:
                        site_rss_map[sid] = peak_rss
    except Exception as e:
        print(f"[ProfilerCore] Error reading {rss_profile_file}: {e}", file=sys.stderr)
        sys.exit(1)

    return site_rss_map

def parse_alloc_trace(trace_file="alloc_trace.txt"):
    if not os.path.exists(trace_file):
        print(f"[ProfilerCore] Error: '{trace_file}' not found!", file=sys.stderr)
        sys.exit(1)

    regions = []
    with open(trace_file, "r") as f:
        for line in f:
            parts = line.strip().split()
            if len(parts) >= 4:
                try:
                    sid = int(parts[0])
                    start_addr = int(parts[1])
                    end_addr = int(parts[2])
                    size = int(parts[3])
                    regions.append({"site_id": sid, "start": start_addr, "end": end_addr, "size": size})
                except ValueError as e:
                    print(f"[ProfilerCore] Error parsing trace line '{line.strip()}': {e}", file=sys.stderr)
                    sys.exit(1)
    return regions

def export_profile_json(sites, site_access_counts, site_rss_map, output_file):
    profile_results = []

    for site in sites:
        sid = site["site_id"]
        if sid not in site_rss_map:
            print(f"[ProfilerCore] Error: Site ID {sid} not found in RSS profile!", file=sys.stderr)
            sys.exit(1)

        rss_bytes = site_rss_map[sid]
        access_count = site_access_counts.get(sid, 0)
        hotness = (access_count / rss_bytes) if rss_bytes > 0 else 0.0

        profile_results.append({
            "site_id": sid,
            "function": site.get("function", "unknown"),
            "file": site.get("file", "unknown"),
            "line": site.get("line", 0),
            "rss_bytes": rss_bytes,
            "access_count": access_count,
            "hotness": round(hotness, 6)
        })

    with open(output_file, "w") as f:
        json.dump(profile_results, f, indent=2)

    print(f"[ProfilerCore] Saved profile data for {len(profile_results)} sites to '{output_file}'")
    return profile_results
